### ISSUE TITLE
As a logged user I want to create a new 7Wonders game

### ISSUE THREAD

**Issue by ziur** [fundacionjala/sevenwonders#1]
- Game form allows define number or players
- Once game is created, it should be listed as an open game
- User is redirected to a waiting page

**Comment by VaniMar** [comment]
1.-Create the form of the game with information: team name, number players and a button "create"
2.- Create a Post for save information the game room when I to do click on the button
3.- Create a page for wait where will show Name of the game, number of players, name who create game with icon difference of the rest team
4.- Consume the service information game created
